//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.27 at 11:07:24 AM EAT 
//


package all.mscdemosoap.com;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="serviceStatus" type="{http://com.mscdemosoap.all}serviceStatus"/&gt;
 *         &lt;element name="bookingId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="clientName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="roomId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="roomType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="roomRate" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="daysBooked" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serviceStatus",
    "bookingId",
    "clientName",
    "roomId",
    "roomType",
    "roomRate",
    "daysBooked",
    "cost"
})
@XmlRootElement(name = "addBookingResponse")
public class AddBookingResponse {

    @XmlElement(required = true)
    protected ServiceStatus serviceStatus;
    protected long bookingId;
    @XmlElement(required = true)
    protected String clientName;
    protected long roomId;
    @XmlElement(required = true)
    protected String roomType;
    protected float roomRate;
    protected long daysBooked;
    protected float cost;

    /**
     * Gets the value of the serviceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceStatus }
     *     
     */
    public ServiceStatus getServiceStatus() {
        return serviceStatus;
    }

    /**
     * Sets the value of the serviceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceStatus }
     *     
     */
    public void setServiceStatus(ServiceStatus value) {
        this.serviceStatus = value;
    }

    /**
     * Gets the value of the bookingId property.
     * 
     */
    public long getBookingId() {
        return bookingId;
    }

    /**
     * Sets the value of the bookingId property.
     * 
     */
    public void setBookingId(long value) {
        this.bookingId = value;
    }

    /**
     * Gets the value of the clientName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * Sets the value of the clientName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientName(String value) {
        this.clientName = value;
    }

    /**
     * Gets the value of the roomId property.
     * 
     */
    public long getRoomId() {
        return roomId;
    }

    /**
     * Sets the value of the roomId property.
     * 
     */
    public void setRoomId(long value) {
        this.roomId = value;
    }

    /**
     * Gets the value of the roomType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomType() {
        return roomType;
    }

    /**
     * Sets the value of the roomType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomType(String value) {
        this.roomType = value;
    }

    /**
     * Gets the value of the roomRate property.
     * 
     */
    public float getRoomRate() {
        return roomRate;
    }

    /**
     * Sets the value of the roomRate property.
     * 
     */
    public void setRoomRate(float value) {
        this.roomRate = value;
    }

    /**
     * Gets the value of the daysBooked property.
     * 
     */
    public long getDaysBooked() {
        return daysBooked;
    }

    /**
     * Sets the value of the daysBooked property.
     * 
     */
    public void setDaysBooked(long value) {
        this.daysBooked = value;
    }

    /**
     * Gets the value of the cost property.
     * 
     */
    public float getCost() {
        return cost;
    }

    /**
     * Sets the value of the cost property.
     * 
     */
    public void setCost(float value) {
        this.cost = value;
    }

}
